name = input (" chaweret tqveni saxeli: ")
surname = input ("chaweret gvari: ")
age= input("chaweret asaki : ")
num1= input("chaweret cifri: ")
num2= input("chaweret meore cifri : ")
print(type(name))
print(type(surname))
print(type(age))
print(type(num1))
print(type(num2))
print(type(num1 + num2))